### PR TITLE
New folder of codes for each lesson of play list!

### PR DESCRIPTION
**Pull request by saif-shines**
I've created this folder for future users to work with pre-written code. I've tested all of these. They are perfectly fine.**I'll add furthur files fine very soon.**
Added comments for larger code for begginners.
Hope it gets merged.

### CODE REVIEW

**Comment by misterhtmlcss** [comment]
Awesome job man!! Good for you.
@saif-shines

**Comment by saif-shines** [comment]
Thank You, @misterhtmlcss 
With such encouragement I could contribute more.

**Comment by iamshaunjp** [comment]
Thanks @Saif-Shines , good work :). I've merged your work and will pop a note on my intro video that you've added practise files for people to work along with! Very kind of you :).

**Comment by saif-shines** [comment]
Very Much thanks to you dear @iamshaunjp , Your Video tutorials are so simple and very attractive that I couldn't resist to contribute. I've suggested you tutorials for about 300 students of our university.

I've found that in each folder, it is going to be [app.js, and other text files]. I'll look on to this and name files professionally, then I'll commit the changes of whole series perfectly. And rewrite the readme file.
Keep uploading videos. 

I've a learnt a lot from you. **Thanks heartfully.** ^_^ !

**Pull request merged**
